root@ubuntu-focal:~# cat compose/docker-compose.yml
version: '3.8'
services:
  vprodb:
    image: vprocontainers/vprofiledb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    depends_on:
      - vprodb

  vpromq01:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - vprocache01

  vproapp:
    image: vprocontainers/vprofileapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    depends_on:
      - vpromq01

  vproweb:
    image: vprocontainers/vprofileweb
    ports:
      - "80:80"
    depends_on:
      - vproapp
volumes:
  vprodbdata: {}
  vproappdata: {}
root@ubuntu-focal:~#
